### ISSUE TITLE
Algolia Search C, C# problem

### ISSUE THREAD

**Issue by Lanson2232** [sdtrdev/source-pocket#172]
**Describe the bug**
Search bug 👌

**To Reproduce**
1. Go to 'Search Box'
2. Type 'C'
3. Then you will see 2 types  of "C" one of them is C**sharp** and the other is **C**

**Expected behavior**
Csharp should be displayed as __CSharp__ or __C#__

**Screenshots**
### C
![Just C](https://i.imgur.com/rV9pmuy.png)
### CSharp
![C Sharp](https://i.imgur.com/7OslRGQ.png)
### C#
![C#](https://i.imgur.com/DOhuzSL.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10 Home Single Language 20H2 (OS BUILD 19042.867)
- Browser, version: Microsoft Edge Version 89.0.774.68 (Official build)

**Comment by damla** [comment]
- Waiting for 24 hours to recrawl event happen.

## Reference

https://docusaurus.io/docs/search#using-algolia-docsearch

**Comment by damla** [comment]
Hi @Lanson2232,

Thanks for informing us about these bugs. Thanks to @algolia, Crawl done its job and the problems you've mentioned are solved!

## CSharp

<p align="center">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/24878421/116008505-99d3f780-a61d-11eb-81f2-6414cb1187db.png">
</p>

## C
<p align="center">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/24878421/116008518-a9534080-a61d-11eb-8547-64f5d59e3c3b.png">
</p>
