### ISSUE TITLE
Header Misnaming

### ISSUE THREAD

**Issue by gblag1** [sdtrdev/source-pocket#22]
**Describe the bug**
Typo in R page.

**To Reproduce**

1. Go to 'https://sourcepocket.netlify.app'
2. Click on 'Source Pocket', then 'R' under 'Programming Languages Pocket' title.
4. See the typo

**Screenshots**
<img width="577" alt="image" src="https://user-images.githubusercontent.com/24878421/101509924-563c6200-398a-11eb-8048-a8517a6f78fa.png">

**Desktop (please complete the following information):**

- OS, version: macOS Catalina 10.15.7
- Browser, version: Safari Version 14.0 (15610.1.28.1.9, 15610)

**Comment by damla** [comment]
*Note*: Issue description edited because it was not written according to **Bug Report** template. Please consider to use for better maintainability of the project.
